# Generated by Django 2.2.4 on 2020-07-24 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0003_home'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mlalgorithm',
            name='parent_endpoint',
        ),
        migrations.RemoveField(
            model_name='mlalgorithmstatus',
            name='parent_mlalgorithm',
        ),
        migrations.RemoveField(
            model_name='mlrequest',
            name='parent_mlalgorithm',
        ),
        migrations.DeleteModel(
            name='ABTest',
        ),
        migrations.DeleteModel(
            name='Endpoint',
        ),
        migrations.DeleteModel(
            name='MLAlgorithm',
        ),
        migrations.DeleteModel(
            name='MLAlgorithmStatus',
        ),
        migrations.DeleteModel(
            name='MLRequest',
        ),
    ]
